name: runam_mobile

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    run: melos exec -- "flutter analyze ."
    description: Run `flutter analyze` in all packages.
  
  test:
    run: melos exec --dir-exists="test" -- "flutter test"
    description: Run `flutter test` for all packages with a test directory.

  clean:
    run: melos exec -- "flutter clean"
    description: Clean all packages.
